# This is a basic workflow to help you get started with Actions

name: Makepdf

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  makepdfs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: mkrakowitzer/actions-makepdfs@master
      if: github.ref == 'refs/heads/master'
      with:
        markdown_dir: doc
        output_dir: tmp
    - uses: actions/upload-artifact@v1
      with:
        name: platform-architecture-docs
        path: tmp

    - name: commit
      run: |
        pwd
        git config --global user.email ${{ secrets.EMAIL }}
        git config --global user.name ${{ secrets.USERNAME }}
        git add .
        git commit -m "update"
        git push